### ISSUE TITLE
Move Expo Doors

### ISSUE THREAD

**Issue by davexoxide** [Lullabot/loungeVR#8]
move expo doors next to logo wall.

In their previous location put the "Hi, We're Lullabot" video.
https://www.youtube.com/watch?v=5xsYDYbTWtA

**Comment by sirkitree** [comment]
depending on if vimeo videos work or not, we might use this one on the booth, outside the lobby

**Comment by sirkitree** [comment]
I see you have the video on the screen, but you're using a websurface. I think we can use the Video tag instead

* [AssetVideo](http://www.dgp.toronto.edu/~mccrae/projects/firebox/notes.html#assetvideo)
* [Video](http://www.dgp.toronto.edu/~mccrae/projects/firebox/notes.html#video)

**Comment by sirkitree** [comment]
Tried this but doesn't seem to be working. I think we might nee dhte actual file locally to do this. Might have to stick with a websurface for now.

**Comment by sirkitree** [comment]
Look like youtube works on pc but not on mac for now. Logged a bug: http://www.reddit.com/r/janusVR/comments/35eq4t/bug422youtube_on_a_websurface_on_mac/

**Comment by davexoxide** [comment]
I was thinking about making a static html file and use the YouTube embed code full screen. This way it will play without all the other YouTube cruft.

**Comment by sirkitree** [comment]
++ though i'm pretty bothered by the fact that youtube doesn't play. might in an embed...

**Comment by sirkitree** [comment]
not that i just added the plane obj instead of using the plane primitive for the websurface object. also switched to vimeo which works on mac and pc
